# Generated by Django 5.0.6 on 2024-05-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollVoted',
            new_name='PollVote',
        ),
    ]
