# Generated by Django 5.0.6 on 2024-05-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pollvoted_pollvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollvote',
            old_name='choice_voted',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='pollvote',
            old_name='question_voted_on',
            new_name='question',
        ),
    ]
