# Generated by Django 5.0.6 on 2024-05-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choice_voted_pollvote_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.voter'),
        ),
    ]
